cleanup in the 'yukon' starter script

diff --git a/tools/yukon b/tools/yukon
--- a/tools/yukon
+++ b/tools/yukon
@@ -1,6 +1,4 @@
-#!/usr/bin/env bash
-
-LIBDIR=${LIBDIR:-'lib'}
+#!/bin/sh
 
 if [ -z "${1}" ]; then
 	echo -e "usage: yukon APPLICATION <ARGS>\n"
@@ -11,67 +9,53 @@ if [ -z "${1}" ]; then
 	echo -e "\nWebpage - http://www.neopsis.com/projects/yukon"
 	echo -e "Version - \$Id$"
 
-else
-	YUKON_DIR="${HOME}/.yukon/${LIBDIR}"
-	YUKON_LIB=(
-		"libFG.so"
-		"libFG.so.1"
-		"libGL.so"
-		"libGL.so.1"
-		"libX11.so"
-		"libX11.so.6"
-		"libX13.so"
-		"libX13.so.6"
-		"libyukon.so"
-	)
+	exit 1
+fi
 
-	# Make sure the user has the yukon directory
-	if [ ! -d "${YUKON_DIR}" ]; then
-		echo "Unable to find ${YUKON_DIR}"
+LIBDIR=${LIBDIR:-'lib'}
+USRDIR="${HOME}/.yukon/${LIBDIR}"
+SYSLIB=( "libGL.so" "libX11.so" )
 
-		exit 1
+# Make sure the user has the yukon directory
+if [ ! -d "${USRDIR}" ]; then
+	echo "Unable to find ${USRDIR}"
+	exit 2
+fi
+
+function MD5Check() {
+	if which md5sum > /dev/null; then
+		local ORIG="$(md5sum /usr/${LIBDIR}/${1} | cut -f 1 -d ' ')"
+
+		if [ -r "${USRDIR}/${1}.md5" ]; then
+			local COPY="$(cat ${USRDIR}/${1}.md5)"
+
+			# Compare them!
+			if [ "${ORIG}" != "${COPY}" ]; then
+				echo "It looks like your locally installed version of ${1} and"
+				echo "the version of ${1} Yukon uses are different. More than"
+				echo "likely your distro has updated one library or the other, and"
+				echo "you should probably rebuild and reinstall Yukon."
+			fi
+		else
+			echo "This version of Yukon does not appear to have created an MD5 checksum for"
+			echo "${1} during installation. To be safe you should reinstall Yukon and"
+			echo "confirm that you have the md5sum binary installed."
+		fi
+	else
+		echo "Unable to find the md5sum binary; skipping comparisons."
+	fi
+}
+
+# Make sure all the libraries exist and have the correct checksum
+for LIB in ${SYSLIB}; do
+	USRLIB="${USRDIR}/${LIB}"
+
+	if [ ! -f "${USRLIB}" ]; then
+		echo "Unable to find library file ${USRLIB}"
+		exit 3
 	fi
 
-	# Make sure all the libraries exist
-	for LIB in ${YUKON_LIB}; do
-		LIBRARY="${YUKON_DIR}/${LIB}"
+	MD5Check ${LIB}
+done
 
-		if [ ! -f "${LIBRARY}" ]; then
-			echo "Unable to find library file ${LIBRARY}"
-
-			exit 2
-		fi
-	done
-
-	function MD5Check() {
-		if which md5sum > /dev/null; then
-			MD5_LOCAL="$(md5sum /usr/${LIBDIR}/lib${1}.so | cut -f 1 -d ' ')"
-			MD5_YUKON=""
-
-			if [ -r "${YUKON_DIR}/lib${1}.so.md5" ]; then
-				MD5_YUKON="$(cat ${YUKON_DIR}/lib${1}.so.md5)"
-
-				# Compare them!
-				if [ "${MD5_LOCAL}" != "${MD5_YUKON}" ]; then
-					echo "It looks like your locally installed version of lib${1} and"
-					echo "the version of lib${1} Yukon uses are different. More than"
-					echo "likely your distro has updated one library or the other, and"
-					echo "you should probably rebuild and reinstall Yukon."
-				fi
-
-			else
-				echo "This version of Yukon does not appear to have created an MD5 checksum for"
-				echo "lib${1} during installation. To be safe you should reinstall Yukon and"
-				echo "confirm that you have the md5sum binary installed."
-			fi
-			
-		else
-			echo "Unable to find the md5sum binary; skipping comparisons."
-		fi
-	}
-
-	MD5Check GL
-	MD5Check X11
-
-	eval "LD_LIBRARY_PATH=${YUKON_DIR}:${LD_LIBRARY_PATH} ${*}"
-fi
+eval "LD_LIBRARY_PATH=${USRDIR}:${LD_LIBRARY_PATH} ${*}"
